### ISSUE TITLE
Use fromp for seq2seq task like speech recognition

### ISSUE THREAD

**Issue by khursani8** [team-approx-bayes/fromp#3]
Hi, is it possible to use fromp for task like speech recognition?
If possible what I should change in the code?

Thanks

**Comment by siddharthswaroop** [comment]
Hi, thanks for your question. Theoretically speaking, it is possible to use FROMP for seq2seq tasks like speech recognition. We have not yet attempted to write code to do this, so I am not sure exactly what changes would be required.

One key difference is having to call the same module many times (so far we have only had to call any single module once per forward/backward pass). This may require changing some parts of the code, such as the forward hook function. I am not sure if more changes would be required.

**Comment by khursani8** [comment]
Hi, thanks for your reply. 

> having to call the same module many times

Sorry, what you mean by call module(model?) many times?
Is it do forward pass for each time frame separately?

Thanks

**Comment by siddharthswaroop** [comment]
Yes, I meant multiple forward passes for each time frame, such as multiple forward passes through the same linear layer. Thanks.

**Comment by khursani8** [comment]
Ohh, ok got it
Thanks
